"""Iterators over nodes."""

import typing

from . import TreeDom, _Node

__all__ = [
    "Ancestors",
    "Children",
    "Descendants",
    "FirstChildren",
    "Iterator",
    "LastChildren",
    "NextSiblings",
    "PrevSiblings",
    "Traverse",
]

@typing.final
class Iterator:
    """Iterates over all of the nodes of a tree in the order they were created, including orphans."""

    def __new__(cls, dom: TreeDom) -> Iterator: ...
    def __iter__(self) -> Iterator: ...
    def __next__(self) -> _Node: ...

@typing.final
class Ancestors:
    def __new__(cls, node: _Node) -> Ancestors: ...
    def __iter__(self) -> Ancestors: ...
    def __next__(self) -> _Node: ...

@typing.final
class PrevSiblings:
    def __new__(cls, node: _Node) -> PrevSiblings: ...
    def __iter__(self) -> PrevSiblings: ...
    def __next__(self) -> _Node: ...

@typing.final
class NextSiblings:
    def __new__(cls, node: _Node) -> NextSiblings: ...
    def __iter__(self) -> NextSiblings: ...
    def __next__(self) -> _Node: ...

@typing.final
class FirstChildren:
    def __new__(cls, node: _Node) -> FirstChildren: ...
    def __iter__(self) -> FirstChildren: ...
    def __next__(self) -> _Node: ...

@typing.final
class LastChildren:
    def __new__(cls, node: _Node) -> LastChildren: ...
    def __iter__(self) -> LastChildren: ...
    def __next__(self) -> _Node: ...

@typing.final
class Children:
    def __new__(cls, node: _Node) -> Children: ...
    def __iter__(self) -> Children: ...
    def __next__(self) -> _Node: ...

@typing.final
class Traverse:
    """Iterates over the edges of a subtree: each node with `False` when opened and `True` when closed."""

    def __new__(cls, node: _Node) -> Traverse: ...
    def __iter__(self) -> Traverse: ...
    def __next__(self) -> tuple[_Node, bool]: ...

@typing.final
class Descendants:
    def __new__(cls, node: _Node) -> Descendants: ...
    def __iter__(self) -> Descendants: ...
    def __next__(self) -> _Node: ...
